### ISSUE TITLE
Can you add shadow color ?

### ISSUE THREAD

**Issue by OuSS-90** [nerdycat/Cupcake#3]
Thank you for this awesome library
Can you add shadow color to shadow() to fill xxx.layer.shadowColor
Cheers,

**Comment by OuSS-90** [comment]
I have other question, What string i need to put in color("") function to set UIColor.clear like color("white") , color("red")

**Comment by nerdycat** [comment]
1. Thank you for your suggestion, I will think about it.
    For now, you simply use the normal way to set shadow color.
2. Use color("clear"), or color(UIColor.clear) if you like.
    Any convenience methods of UIColor (like darkGary, cyan, clear, etc) can be set as string.

**Comment by OuSS-90** [comment]
Thank you for you quick response.
color("clear") doesn't work, it give me black background

**Comment by nerdycat** [comment]
Fixed that, also shadow color has been added. Happy coding ^^

**Comment by OuSS-90** [comment]
Thank you very much 👍
