### ISSUE TITLE
Update constraint added in storyboard

### ISSUE THREAD

**Issue by OuSS-90** [nerdycat/Cupcake#4]
I have two view (view1 and view2) in storyboard and i have constraints top space between them,
I want to update it by code, i did this:

view2.remakeCons({
       $0.top.equal(view1).bottom.offset(40)
})

But i got this error: 
'Unable to activate constraint with anchors <NSLayoutYAxisAnchor:0x1c4a70e00 "UIView:0x13dd5e590.top"> and <NSLayoutYAxisAnchor:0x1c067ca00 "View1:0x13de2fd70.bottom"> because they have no common ancestor.  Does the constraint or its anchors reference items in different view hierarchies?  That's illegal.'

**Comment by OuSS-90** [comment]
I can update constraint made by storyboards or it just add new one ?
cause even changing height from 60 to 0 i have this warning:

Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x1c028dbb0 UIView:0x147d74210.height == 60   (active)>",
    "<NSLayoutConstraint:0x1c028bc70 UIView:0x147d74210.height == 0   (active)>"
)

it add new constraint, not update it

**Comment by nerdycat** [comment]
Sadly, you can only update or remake constraints that are made by makeCons() earlier.
a.k.a you can not mix use Cupcake, SnapKit and NSLayoutConstraint (either created directly or by Storyboard) when come to updating constraints. Otherwise it will simply add new constraints.

**Comment by OuSS-90** [comment]
Ok thank you
