### ISSUE TITLE
UIBarButtonItem no onclick ?

### ISSUE THREAD

**Issue by davamp** [nerdycat/Cupcake#7]

**Comment by nerdycat** [comment]
Sorry, there are not extensions for UIBarButtonItem, since it is not a subview of UIView.

**Comment by davamp** [comment]
That’s sad :( I hope you have it in the new version. Thanks I appreciate it :)

**Comment by nerdycat** [comment]
Good idea actually :)

**Comment by davamp** [comment]
Yes

**Comment by nerdycat** [comment]
Added ^^

**Comment by davamp** [comment]
Wow amazing man !! Thanks so much
