### ISSUE TITLE
Compiling as Swift 4.2, with 'Cupcake' built as Swift 4.1.50 "Xcode 10"

### ISSUE THREAD

**Issue by OuSS-90** [nerdycat/Cupcake#9]
Hi, I got this error when using xCode 10 with swift 4.2

`compiling as Swift 4.2, with 'Cupcake' built as Swift 4.1.50 (this is supported but may expose additional compiler issues)`

**Comment by nerdycat** [comment]
Fixed :）

**Comment by OuSS-90** [comment]
Thanks
